vim.keymap.set("n", "<leader>jt", function()
  vim.cmd("JavaTestRunCurrentClass")
end)
vim.keymap.set("n", "<leader>dt", function()
  vim.cmd("JavaTestDebugCurrentClass")
end)
vim.keymap.set("n", "<leader>jr", function()
  vim.cmd("JavaTestViewLastReport")
end)
